version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: playlist_local_django
    container_name: django
    depends_on:
      - postgres_playlist
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres_playlist:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: playlist_production_postgres
    container_name: postgres_playlist
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: playlist_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./playlist:/app/playlist:z
    ports:
      - "7000:7000"
    command: /start-docs

  redis_playlist:
    image: redis:5.0
    container_name: redis_playlist

  celeryworker:
    <<: *django
    image: playlist_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis_playlist
      - postgres_playlist
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: playlist_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis_playlist
      - postgres_playlist
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: playlist_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower
